services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-greenlight
    environment:
      - POSTGRES_USER=greenlight
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=greenlight
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
